const DEFAULT_CATEGORIES=[
  {name:"Makanan",icon:"🍜",type:"expense"},{name:"Transportasi",icon:"🚕",type:"expense"},{name:"Belanja",icon:"🛒",type:"expense"},{name:"Kos / Rumah",icon:"🏠",type:"expense"},{name:"Tagihan",icon:"💡",type:"expense"},{name:"Pendidikan",icon:"📚",type:"expense"},{name:"Hiburan",icon:"🎮",type:"expense"},{name:"Kesehatan",icon:"✚",type:"expense"},{name:"Tabungan",icon:"💰",type:"both"},{name:"Gaji",icon:"💼",type:"income"},{name:"Bonus",icon:"★",type:"income"},{name:"Mukafaah",icon:"💰",type:"income"},{name:"Lainnya",icon:"•",type:"both"}
];
const DEFAULT_SETTINGS={appName:"Website Data Keuangan",background:"",personalContact:{name:"",phone:"",whatsapp:"",email:"",instagram:""}};
const OFFICIAL_SUPPORT={instagram:"@akh_rukyan",youtube:"@akhsubhan",email:"akhsubhan02@gmail.com",supportUrl:""};
const LOCAL={tx:"df_transactions_v3_cache",notes:"df_notes_v3_cache",quick:"df_quick_note_v3_cache",theme:"df_theme_v3_cache",categories:"df_categories_v3_cache",settings:"df_settings_v3_cache",needs:"df_monthly_needs_v3_cache"};
let transactions=[],notes=[],categories=[],settings={...DEFAULT_SETTINGS},monthlyNeeds=[],quickNote="",currentType="income",currentFilter="all",deleteTarget=null,editingId=null,needMonth=new Date();
let supabaseClient=null,currentUser=null,saveTimer=null;
const $=id=>document.getElementById(id);
const money=n=>new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(Number(n)||0);
const dateLabel=s=>new Date(s+"T00:00:00").toLocaleDateString("id-ID",{day:"2-digit",month:"short",year:"numeric"});
const makeId=()=>window.crypto?.randomUUID?.()||Date.now().toString(36)+Math.random().toString(36).slice(2);
const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
const monthKey=d=>{const y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,"0");return `${y}-${m}`};
const monthLabel=d=>d.toLocaleDateString("id-ID",{month:"long",year:"numeric"});

function toast(msg){const el=$("toast");el.textContent=msg;el.classList.add("show");clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>el.classList.remove("show"),2500)}
function setDate(){if(!$("date").value)$("date").value=new Date().toISOString().slice(0,10)}
function localPayload(){return {transactions,notes,quickNote,categories,settings,monthlyNeeds,theme:document.body.classList.contains("light")?"light":"dark"}}
function saveLocal(){const p=localPayload();localStorage.setItem(LOCAL.tx,JSON.stringify(p.transactions));localStorage.setItem(LOCAL.notes,JSON.stringify(p.notes));localStorage.setItem(LOCAL.quick,p.quickNote);localStorage.setItem(LOCAL.categories,JSON.stringify(p.categories));localStorage.setItem(LOCAL.settings,JSON.stringify(p.settings));localStorage.setItem(LOCAL.needs,JSON.stringify(p.monthlyNeeds));localStorage.setItem(LOCAL.theme,p.theme)}
function normalizeCategories(list){const result=Array.isArray(list)&&list.length?list.map(c=>({name:String(c.name||"Lainnya"),icon:String(c.icon||"•"),type:["both","income","expense"].includes(c.type)?c.type:"both"})):DEFAULT_CATEGORIES.map(c=>({...c}));if(!result.some(c=>c.name.toLowerCase()==="mukafaah"))result.push({name:"Mukafaah",icon:"💰",type:"income"});return result}
function normalizeSettings(raw){const r=raw&&typeof raw==="object"?raw:{};return {...DEFAULT_SETTINGS,...r,personalContact:{...DEFAULT_SETTINGS.personalContact,...(r.personalContact||{})}}}
function loadLocal(){try{transactions=JSON.parse(localStorage.getItem(LOCAL.tx)||"[]");notes=JSON.parse(localStorage.getItem(LOCAL.notes)||"[]");quickNote=localStorage.getItem(LOCAL.quick)||"";categories=normalizeCategories(JSON.parse(localStorage.getItem(LOCAL.categories)||"null"));settings=normalizeSettings(JSON.parse(localStorage.getItem(LOCAL.settings)||"{}")||{});monthlyNeeds=JSON.parse(localStorage.getItem(LOCAL.needs)||"[]");if(localStorage.getItem(LOCAL.theme)==="light")document.body.classList.add("light")}catch{transactions=[];notes=[];categories=DEFAULT_CATEGORIES.map(c=>({...c}));settings=normalizeSettings();monthlyNeeds=[]}}
function hasLocalData(){return transactions.length||notes.length||monthlyNeeds.length||quickNote}
function scheduleCloudSave(){saveLocal();if(!currentUser||!supabaseClient)return;clearTimeout(saveTimer);saveTimer=setTimeout(saveCloud,650)}
async function saveCloud(){if(!currentUser)return;const {error}=await supabaseClient.from("user_data").upsert({user_id:currentUser.id,payload:localPayload(),updated_at:new Date().toISOString()},{onConflict:"user_id"});if(error)toast("Data lokal tersimpan, tetapi sinkronisasi gagal.")}

function renderAuth(view="login"){document.querySelectorAll(".auth-tab").forEach(b=>b.classList.toggle("active",b.dataset.authView===view));$("loginForm").classList.toggle("hidden-auth",view!=="login");$("registerForm").classList.toggle("hidden-auth",view!=="register");$("authMessage").textContent=""}
function authMessage(msg,error=false){const el=$("authMessage");el.textContent=msg;el.className="auth-message"+(error?" error":"")}
function showApp(){$("authGate").classList.add("hidden-auth-gate");$("appShell").classList.remove("hidden-ui");$("splash").classList.remove("hidden-ui");setTimeout(()=>$("splash").classList.add("hide"),900);setTimeout(()=>$('splash').classList.add('hidden-ui'),1600)}
function showAuth(){currentUser=null;$("appShell").classList.add("hidden-ui");$("splash").classList.add("hidden-ui");$("authGate").classList.remove("hidden-auth-gate");renderAuth("login")}

async function loadCloud(){
  loadLocal();
  const {data,error}=await supabaseClient.from("user_data").select("payload").eq("user_id",currentUser.id).maybeSingle();
  if(error){toast("Gagal mengambil data cloud. Coba refresh.");return}
  if(data?.payload && Object.keys(data.payload).length){applyPayload(data.payload);saveLocal();await saveCloud();return}
  if(hasLocalData()){await saveCloud();toast("Data lama dari perangkat ini berhasil disinkronkan.");return}
  saveLocal();await saveCloud();
}
function applyPayload(p){transactions=Array.isArray(p.transactions)?p.transactions:[];notes=Array.isArray(p.notes)?p.notes:[];categories=normalizeCategories(p.categories);settings=normalizeSettings(p.settings);monthlyNeeds=Array.isArray(p.monthlyNeeds)?p.monthlyNeeds:[];quickNote=String(p.quickNote||"");document.body.classList.toggle("light",p.theme==="light");$("themeToggle").textContent=p.theme==="light"?"☀":"☾"}

function applySettings(){
  document.title=settings.appName||DEFAULT_SETTINGS.appName;
  document.querySelectorAll(".brand strong").forEach(e=>e.textContent=settings.appName||DEFAULT_SETTINGS.appName);
  const footerTitle=document.querySelector(".footer-brand h2");if(footerTitle)footerTitle.textContent=(settings.appName||DEFAULT_SETTINGS.appName).toUpperCase();
  const hero=$("view-home")?.querySelector(".hero-image");if(hero)hero.style.backgroundImage=settings.background?`url("${settings.background}")`:"url('assets/uang.jpg')";
  $("appNameInput").value=settings.appName;$("settingsUserEmail").textContent=currentUser?.email||"-";$("userEmailLabel").textContent=currentUser?.email||"Akun";
  const pc=settings.personalContact||{};$("personalNameInput").value=pc.name||"";$("personalPhoneInput").value=pc.phone||"";$("personalWhatsappInput").value=pc.whatsapp||"";$("personalEmailInput").value=pc.email||"";$("personalInstagramInput").value=pc.instagram||"";renderPersonalContactPreview();
  renderCategorySelect();renderCategoryManager();renderNeeds();$("quickNote").value=quickNote;
}
function renderPersonalContactPreview(){const pc=settings.personalContact||{};const items=[["Nama",pc.name],["No. HP",pc.phone],["WhatsApp",pc.whatsapp],["Email pribadi",pc.email],["Instagram",pc.instagram]];const el=$("personalContactPreview");if(!el)return;el.innerHTML=items.map(([label,value])=>`<div class="contact-preview-item"><span>${label}</span><b>${esc(value||"Belum diisi")}</b></div>`).join("")}
function renderCategorySelect(){const select=$("category");const available=categories.filter(c=>c.type==="both"||c.type===currentType);const old=select.value;select.innerHTML=available.map(c=>`<option value="${esc(c.name)}">${esc(c.icon)} ${esc(c.name)}</option>`).join("");if(available.some(c=>c.name===old))select.value=old}
function renderCategoryManager(){const el=$("categoryManager");el.innerHTML=categories.map((c,i)=>`<div class="managed-category"><div class="managed-left"><span class="managed-icon">${esc(c.icon)}</span><div><b>${esc(c.name)}</b><small>${c.type==="both"?"Pemasukan & Pengeluaran":c.type==="income"?"Pemasukan":"Pengeluaran"}</small></div></div><div class="managed-actions"><button class="small-btn" onclick="editCategory(${i})">✎</button><button class="small-btn" onclick="deleteCategory(${i})">×</button></div></div>`).join("")}
function openCategoryModal(index=null){$("categoryModal").classList.remove("hidden");window.categoryEditIndex=index;$("categoryModalTitle").textContent=index===null?"Tambah kategori":"Edit kategori";const c=index===null?{name:"",icon:"",type:"both"}:categories[index];$("categoryNameInput").value=c.name;$("categoryIconInput").value=c.icon;$("categoryTypeInput").value=c.type}
function closeCategoryModal(){$("categoryModal").classList.add("hidden");window.categoryEditIndex=null}
function saveCategoryForm(){const name=$("categoryNameInput").value.trim(),icon=$("categoryIconInput").value.trim()||"•",type=$("categoryTypeInput").value;if(!name)return toast("Nama kategori belum diisi.");const duplicate=categories.some((c,i)=>c.name.toLowerCase()===name.toLowerCase()&&i!==window.categoryEditIndex);if(duplicate)return toast("Kategori dengan nama itu sudah ada.");if(window.categoryEditIndex===null)categories.push({name,icon,type});else categories[window.categoryEditIndex]={name,icon,type};scheduleCloudSave();applySettings();closeCategoryModal();toast("Kategori disimpan.")}
function editCategory(i){openCategoryModal(i)}
function deleteCategory(i){const c=categories[i];if(categories.length<=1)return toast("Minimal satu kategori harus ada.");if(confirm(`Hapus kategori "${c.name}"? Transaksi lama tetap tersimpan.`)){categories.splice(i,1);scheduleCloudSave();applySettings();toast("Kategori dihapus.")}}
window.editCategory=editCategory;window.deleteCategory=deleteCategory;

function totals(){const income=transactions.filter(t=>t.type==="income").reduce((a,t)=>a+Number(t.amount),0),expense=transactions.filter(t=>t.type==="expense").reduce((a,t)=>a+Number(t.amount),0);return{income,expense,balance:income-expense}}
function updateDashboard(){const t=totals();$("homeBalance").textContent=money(t.balance);$("homeIncome").textContent=money(t.income);$("homeExpense").textContent=money(t.expense);$("dataBalance").textContent=money(t.balance);$("dataIncome").textContent=money(t.income);$("dataExpense").textContent=money(t.expense);$("analysisIncome").textContent=money(t.income);$("analysisExpense").textContent=money(t.expense);const max=Math.max(t.income,t.expense,1);$("incomeBar").style.height=t.income/max*190+"px";$("expenseBar").style.height=t.expense/max*190+"px";renderTransactions();renderCategories();renderNotes();renderNeeds();$("quickNote").value=quickNote;const msg=$("analysisMessage"),sub=$("analysisSubmessage");if(!transactions.length){msg.textContent="Belum ada transaksi.";sub.textContent="Mulai catat pemasukan dan pengeluaran untuk mendapatkan insight."}else if(t.income===0){msg.textContent="Pengeluaranmu sedang tercatat.";sub.textContent=`Total pengeluaran sejauh ini ${money(t.expense)}.`}else{const ratio=t.expense/t.income*100;msg.textContent=ratio<=50?"Keuanganmu masih cukup terkendali.":"Pengeluaran mulai mengambil porsi besar dari pemasukan.";sub.textContent=`Pengeluaran saat ini sekitar ${ratio.toFixed(0)}% dari total pemasukan.`}}
function iconFor(cat){return categories.find(c=>c.name===cat)?.icon||"•"}
function renderTransactions(){const q=$("searchInput").value.toLowerCase().trim();let list=transactions.filter(t=>(currentFilter==="all"||t.type===currentFilter)&&(`${t.description} ${t.category} ${t.method}`.toLowerCase().includes(q)));list.sort((a,b)=>b.date.localeCompare(a.date)||Number(b.createdAt)-Number(a.createdAt));$("transactionList").innerHTML=list.length?list.map(t=>`<div class="transaction-item"><div class="transaction-icon">${iconFor(t.category)}</div><div class="transaction-info"><b>${esc(t.description)}</b><small>${esc(t.category)} • ${esc(t.method)}${t.note?` • ${esc(t.note)}`:""}</small></div><div class="transaction-date">${dateLabel(t.date)}</div><div class="transaction-amount ${t.type}">${t.type==="income"?"+":"−"} ${money(t.amount)}</div><div class="transaction-actions"><button class="small-btn" onclick="editTransaction('${t.id}')">✎</button><button class="small-btn" onclick="askDelete('${t.id}')">×</button></div></div>`).join(""):"<div class='empty'>Belum ada transaksi yang cocok.</div>"}
function renderCategories(){const map={};transactions.filter(t=>t.type==="expense").forEach(t=>map[t.category]=(map[t.category]||0)+Number(t.amount));const rows=Object.entries(map).sort((a,b)=>b[1]-a[1]),total=rows.reduce((a,[,v])=>a+v,0);$("categoryBreakdown").innerHTML=rows.length?rows.map(([cat,val])=>`<div class="category-row"><span>${iconFor(cat)} ${esc(cat)}</span><div class="category-track"><i style="width:${total?val/total*100:0}%"></i></div><small>${money(val)}</small></div>`).join(""):"<div class='empty'>Belum ada pengeluaran.</div>"}
function renderNotes(){const count=notes.length;const c=$("notesCount");if(c)c.textContent=`${count} catatan`;$("notesList").innerHTML=count?notes.slice().sort((a,b)=>b.createdAt-a.createdAt).map(n=>`<article class="saved-note"><button class="small-btn" onclick="deleteNote('${n.id}')" title="Hapus catatan">×</button><p>${esc(n.text)}</p><small>${new Date(n.createdAt).toLocaleString("id-ID",{dateStyle:"medium",timeStyle:"short"})}</small></article>`).join(""):"<div class='empty' style='grid-column:1/-1'>Belum ada catatan. Tulis catatan pertamamu di atas.</div>"}
function addNote(text){text=text.trim();if(!text)return toast("Catatan masih kosong.");notes.push({id:makeId(),text,createdAt:Date.now()});$("noteInput").value="";scheduleCloudSave();updateDashboard();toast("Catatan tersimpan.")}
function deleteNote(id){notes=notes.filter(n=>n.id!==id);scheduleCloudSave();updateDashboard();toast("Catatan dihapus.")}
window.deleteNote=deleteNote;

function renderNeeds(){const key=monthKey(needMonth),done=monthlyNeeds.filter(n=>n.checkedByMonth?.[key]).length;$("needMonthLabel").textContent=monthLabel(needMonth);$("needProgress").textContent=`${done} dari ${monthlyNeeds.length} kebutuhan selesai`;const el=$("needsList");el.innerHTML=monthlyNeeds.length?monthlyNeeds.map(n=>{const checked=!!n.checkedByMonth?.[key];return `<div class="need-item ${checked?"checked":""}"><label><input type="checkbox" ${checked?"checked":""} onchange="toggleNeed('${n.id}',this.checked)"><span class="custom-check">✓</span><b>${esc(n.text)}</b></label><button class="small-btn" onclick="deleteNeed('${n.id}')">×</button></div>`}).join(""):"<div class='empty'>Belum ada kebutuhan bulanan. Tambahkan kebutuhan inti yang ingin selalu kamu ingat.</div>"}
function addNeed(){const text=$("needInput").value.trim();if(!text)return toast("Tulis kebutuhan dulu.");monthlyNeeds.push({id:makeId(),text,checkedByMonth:{}});$("needInput").value="";scheduleCloudSave();renderNeeds();toast("Kebutuhan bulanan ditambahkan.")}
function toggleNeed(id,checked){const n=monthlyNeeds.find(x=>x.id===id);if(!n)return;n.checkedByMonth=n.checkedByMonth||{};n.checkedByMonth[monthKey(needMonth)]=checked;scheduleCloudSave();renderNeeds()}
function deleteNeed(id){monthlyNeeds=monthlyNeeds.filter(n=>n.id!==id);scheduleCloudSave();renderNeeds();toast("Kebutuhan dihapus.")}
window.toggleNeed=toggleNeed;window.deleteNeed=deleteNeed;

function navigate(view){document.querySelectorAll(".view").forEach(v=>v.classList.remove("active-view"));$("view-"+view).classList.add("active-view");document.querySelectorAll(".nav-item").forEach(b=>b.classList.toggle("active",b.dataset.view===view));$("sidebar").classList.remove("open");window.scrollTo({top:0,behavior:"smooth"})}
function toggleTheme(){const light=document.body.classList.toggle("light");$("themeToggle").textContent=light?"☀":"☾";scheduleCloudSave()}
function exportCSV(){const header=["Tanggal","Jenis","Nominal","Keterangan","Kategori","Metode","Catatan"],rows=transactions.slice().sort((a,b)=>a.date.localeCompare(b.date)).map(t=>[t.date,t.type==="income"?"Pemasukan":"Pengeluaran",t.amount,t.description,t.category,t.method,t.note||""]);const csv=[header,...rows].map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(",")).join("\n");const blob=new Blob(["\ufeff"+csv],{type:"text/csv;charset=utf-8"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`data-keuangan-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(a.href);toast("CSV dibuat.")}
function exportJSON(){const blob=new Blob([JSON.stringify(localPayload(),null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`data-keuangan-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href);toast("Backup JSON dibuat.")}
function importJSON(file){if(!file)return;const r=new FileReader();r.onload=()=>{try{const d=JSON.parse(r.result);applyPayload(d);scheduleCloudSave();updateDashboard();toast("Backup berhasil diimpor dan disinkronkan.")}catch{toast("File backup tidak valid.")}};r.readAsText(file)}

function editTransaction(id){const t=transactions.find(x=>x.id===id);if(!t)return;editingId=id;currentType=t.type;$("amount").value=t.amount;$("description").value=t.description;renderCategorySelect();$("category").value=t.category;$("date").value=t.date;$("method").value=t.method;$("transactionNote").value=t.note||"";document.querySelectorAll(".type-btn").forEach(b=>b.classList.toggle("selected",b.dataset.type===currentType));navigate("home");window.scrollTo({top:document.querySelector(".transaction-form").offsetTop-90,behavior:"smooth"});toast("Mode edit aktif.")}
window.editTransaction=editTransaction;
function askDelete(id){deleteTarget=id;$("modalTitle").textContent="Hapus transaksi?";$("modalText").textContent="Data yang dihapus tidak dapat dikembalikan.";$("modal").classList.remove("hidden")}
window.askDelete=askDelete;
function closeModal(){$("modal").classList.add("hidden");deleteTarget=null}

async function logout(){await supabaseClient.auth.signOut();showAuth()}

async function bootUser(session){currentUser=session.user;await loadCloud();applySettings();updateDashboard();setDate();showApp()}
async function init(){
  loadLocal();
  const cfg=window.SUPABASE_CONFIG||{};
  if(!window.supabase?.createClient||!cfg.url||cfg.url.includes("YOUR-PROJECT")||!cfg.anonKey||cfg.anonKey.includes("YOUR_SUPABASE")){authMessage("Website belum terhubung ke Supabase. Isi supabase-config.js terlebih dahulu.",true);return}
  supabaseClient=window.supabase.createClient(cfg.url,cfg.anonKey);
  const {data}=await supabaseClient.auth.getSession();
  if(data.session)await bootUser(data.session);else showAuth();
  supabaseClient.auth.onAuthStateChange(async(_event,session)=>{if(session&&session.user?.id!==currentUser?.id)await bootUser(session);if(!session)showAuth()});
}

document.querySelectorAll(".auth-tab").forEach(b=>b.onclick=()=>renderAuth(b.dataset.authView));
$("loginForm").onsubmit=async e=>{e.preventDefault();authMessage("Memeriksa akun...");const {error}=await supabaseClient.auth.signInWithPassword({email:$("loginEmail").value.trim(),password:$("loginPassword").value});if(error)authMessage(error.message,true)};
$("registerForm").onsubmit=async e=>{e.preventDefault();const email=$("registerEmail").value.trim(),p=$("registerPassword").value,p2=$("registerPassword2").value;if(p!==p2)return authMessage("Password tidak sama.",true);authMessage("Membuat akun...");const {data,error}=await supabaseClient.auth.signUp({email,password:p});if(error)return authMessage(error.message,true);if(data.session)authMessage("Akun berhasil dibuat. Membuka website...");else authMessage("Akun berhasil dibuat. Cek email untuk verifikasi, lalu masuk." )};
$("forgotPassword").onclick=async()=>{const email=$("loginEmail").value.trim();if(!email)return authMessage("Isi email dulu untuk menerima link reset password.",true);const {error}=await supabaseClient.auth.resetPasswordForEmail(email,{redirectTo:location.origin+location.pathname});authMessage(error?error.message:"Link reset password sudah dikirim. Cek emailmu.",!!error)};

document.querySelectorAll(".nav-item").forEach(b=>b.onclick=()=>navigate(b.dataset.view));$("showDataBtn").onclick=()=>navigate("data");document.querySelectorAll(".type-btn").forEach(btn=>btn.onclick=()=>{currentType=btn.dataset.type;document.querySelectorAll(".type-btn").forEach(b=>b.classList.remove("selected"));btn.classList.add("selected");renderCategorySelect()});
$("transactionForm").onsubmit=e=>{e.preventDefault();const amount=Number($("amount").value),description=$("description").value.trim();if(!amount||amount<=0)return toast("Masukkan nominal yang benar.");if(!description)return toast("Keterangan belum diisi.");const obj={id:editingId||makeId(),type:currentType,amount,description,category:$("category").value,date:$("date").value,method:$("method").value,note:$("transactionNote").value.trim(),createdAt:Date.now()};if(editingId){const i=transactions.findIndex(t=>t.id===editingId);if(i>=0)transactions[i]=obj;editingId=null;toast("Transaksi diperbarui.")}else{transactions.push(obj);toast("Transaksi berhasil disimpan.")}scheduleCloudSave();updateDashboard();e.target.reset();currentType="income";document.querySelectorAll(".type-btn").forEach(b=>b.classList.toggle("selected",b.dataset.type==="income"));renderCategorySelect();setDate()};

document.querySelectorAll(".filter-btn").forEach(b=>b.onclick=()=>{currentFilter=b.dataset.filter;document.querySelectorAll(".filter-btn").forEach(x=>x.classList.toggle("active",x===b));renderTransactions()});$("searchInput").oninput=renderTransactions;
$("addNoteBtn").onclick=()=>addNote($("noteInput").value);$("saveQuickNote").onclick=()=>{const text=$("quickNote").value.trim();if(!text)return toast("Catatan masih kosong.");addNote(text);quickNote="";$("quickNote").value="";};$("addNeedBtn").onclick=addNeed;$("needInput").addEventListener("keydown",e=>{if(e.key==="Enter")addNeed()});$("prevMonth").onclick=()=>{needMonth.setMonth(needMonth.getMonth()-1);renderNeeds()};$("nextMonth").onclick=()=>{needMonth.setMonth(needMonth.getMonth()+1);renderNeeds()};$("todayMonth").onclick=()=>{needMonth=new Date();renderNeeds()};
$("themeToggle").onclick=toggleTheme;$("settingsTheme").onclick=toggleTheme;$("logoutBtn").onclick=logout;$("settingsLogout").onclick=logout;$("menuToggle").onclick=()=>$("sidebar").classList.toggle("open");$("exportBtn").onclick=exportCSV;$("exportJsonBtn").onclick=exportJSON;$("importJsonInput").onchange=e=>importJSON(e.target.files[0]);$("clearDataBtn").onclick=()=>{deleteTarget="ALL";$("modalTitle").textContent="Hapus semua transaksi?";$("modalText").textContent="Seluruh riwayat transaksi akan dihapus dari akunmu.";$("modal").classList.remove("hidden")};
$("closeModal").onclick=closeModal;$("cancelModal").onclick=closeModal;$("confirmModal").onclick=()=>{if(deleteTarget==="ALL")transactions=[];else if(deleteTarget)transactions=transactions.filter(t=>t.id!==deleteTarget);scheduleCloudSave();updateDashboard();toast("Data diperbarui.");closeModal()};
$("addCategoryBtn").onclick=()=>openCategoryModal();$("saveCategory").onclick=saveCategoryForm;$("cancelCategory").onclick=closeCategoryModal;$("closeCategoryModal").onclick=closeCategoryModal;$("savePersonalContact").onclick=()=>{settings.personalContact={name:$("personalNameInput").value.trim(),phone:$("personalPhoneInput").value.trim(),whatsapp:$("personalWhatsappInput").value.trim(),email:$("personalEmailInput").value.trim(),instagram:$("personalInstagramInput").value.trim()};scheduleCloudSave();applySettings();toast("Kontak pribadi disimpan.")};$("saveAppName").onclick=()=>{const n=$("appNameInput").value.trim();if(!n)return toast("Nama aplikasi belum diisi.");settings.appName=n;scheduleCloudSave();applySettings();toast("Nama aplikasi diperbarui.")};$("bgImageInput").onchange=e=>{const file=e.target.files[0];if(!file)return;if(file.size>2500000){toast("Gunakan gambar maksimal 2.5 MB.");e.target.value="";return}const r=new FileReader();r.onload=()=>{settings.background=r.result;scheduleCloudSave();applySettings();toast("Background diperbarui.")};r.readAsDataURL(file)};$("resetBgBtn").onclick=()=>{settings.background="";scheduleCloudSave();applySettings();toast("Background dikembalikan.")};

document.addEventListener("keydown",e=>{if(e.key==="Escape"){closeModal();closeCategoryModal()}if(e.key==="Enter"&&document.activeElement.tagName!=="TEXTAREA"&&document.activeElement.tagName!=="BUTTON"&&$("view-home").classList.contains("active-view"))$("transactionForm").requestSubmit()});
init();
